name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # setiap hari tengah malam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3
        with:
          github_user_name: Mhusnul
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
